/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.unsch.collection;

/**
 * @author jhon
 * @author fernado
 **/
public class Library {

    public static final String VERSION = "1.0.0";
    public static final String[] authors = {"Jhon samuel fernandez gutierrez", "Fernando bosh lope beltrán"};

    public boolean someLibraryMethod() {
        return true;
    }
}
